worker_processes 1;

events { 
    worker_connections 1024; 
}

http {
    # 'backend' — сервис в docker-compose
    upstream effective_backend {
        server backend:8080;
    }

    server {
        # Слушаем 80 порт (внешний)
        listen 80;
        server_name localhost;

        # Корень
        location / {
            # Отправляем на upstream
            proxy_pass http://effective_backend;

            # Пробрасываем важные заголовки
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Отключаем лишние редиректы
            proxy_redirect off;
        }
    }
}